### ISSUE TITLE
Segfault when applying a texture (likely guislider related).

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#327]
To reproduce: In editing mode, select anywhere in a map, press F1, and select a random texture.

Backtrace:
```
#0  __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x00007fffec1e2faf in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fffec41fa3b in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fffec1e4e36 in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffec08143f in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007fffec0537ba in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fffec053ad4 in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffec053b7b in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x0000000000411766 in gle::drawquads (offset=4078, count=75)
    at shared/glemu.cpp:96
#9  0x00000000004122a2 in gle::end () at shared/glemu.cpp:296
#10 0x00000000005bd3c4 in gui::skin (this=0x3db17f0, x1=3647, y1=-3432, 
    x2=3811, y2=-264, c1=0, b1=0.300000012, c2=12632256, b2=1, skinborder=true)
    at engine/ui.cpp:203
#11 0x00000000005c32a0 in gui::slider_ (this=0x3db17f0, size=164, percent=0, 
    space=198, hit=@0x7fffffffdc93: false, style=0, colour=-1)
    at engine/ui.cpp:1061
#12 0x00000000005c0074 in gui::slider (this=0x3db17f0, val=@0xa9f150: 0, 
    vmin=0, vmax=1, colour=16777215, label=0x0, reverse=true, scroll=true, 
    style=0, scolour=-1) at engine/ui.cpp:633
#13 0x00000000004bd125 in texturegui::gui (this=0xa9f140 <gui>, g=..., 
    firstpass=false) at engine/octaedit.cpp:2601
#14 0x00000000005b7aac in UI::render () at engine/ui.cpp:1438
#15 0x00000000006a6bcb in hud::drawlast () at game/hud.cpp:1610
#16 0x00000000004f8b89 in drawviewtype (targtype=2) at engine/rendergl.cpp:2169
#17 0x00000000004f8f1f in gl_drawframe (w=1920, h=1080)
    at engine/rendergl.cpp:2230
#18 0x000000000047b343 in main (argc=1, argv=0x7fffffffdfc8)
    at engine/main.cpp:1042
```

**Comment by qreeves** [comment]
Fixed.
