### ISSUE TITLE
Running decalreset while active decals are placed will segfault.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#774]
# Reproduction
* `/edit somenewmap`
* Raise a wall out of the ground.
* `/newent decal` after selecting the wall while facing it.
* Modify the decal until it is visible.
* `/decalreset`

# Backtrace
```
#0  0x00000000006613c0 in changebatchtmus (cur=..., pass=0, b=...) at engine/renderva.cpp:2297
No locals.
#1  0x00000000006619ce in renderdecalbatches (cur=..., pass=0) at engine/renderva.cpp:2406
        b = @0x3f83850: {es = @0x19f10a0, slot = @0xd0eaa0, offset = 0, va = 0x3ef8160, next = -1, batch = -1}
        curbatch = -1
#2  0x0000000000661cb5 in renderdecals () at engine/renderva.cpp:2477
        decalva = 0x3ef8160
        cur = {vbuf = 72, colorscale = {{{x = 1, y = 1, z = 1}, {r = 1, g = 1, b = 1}, v = {1, 1, 1}}}, globals = -1, tmu = -1, textures = {0, 0, 0, 0, 0, 0, 0}, slot = 0x0}
#3  0x00000000005b6bb8 in rendergbuffer (depthclear=true) at engine/renderlights.cpp:4852
        gcputimer = 0x0
        gtimer = 0x0
#4  0x0000000000597dda in gl_drawview () at engine/rendergl.cpp:2302
        scalefbo = 4
        fogmargin = 1.94000006
        fogmat = 0
        abovemat = 0
        fogbelow = 0
#5  0x0000000000598576 in gl_drawframe () at engine/rendergl.cpp:2458
        noview = false
#6  0x000000000051bf9d in main (argc=1, argv=0x7fffffffe038) at engine/main.cpp:1143
        elapsed = 8
        frameloops = 2978
        initscript = 0x0
        reprotoprefix = "redeclipse://"
        reprotolen = 13
        reprotoarg = 0x0
        connectstr = 0x0
        connectpassword = 0x0
        connecthost = 0x0
        connectport = 28801
```

**Comment by lsalzman** [comment]
Fixed
